# Generated by Django 4.2.7 on 2025-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand (e.g., Crucial, Samsung, Apple)', max_length=100, null=True),
        ),
    ]
